# =============================================================================
# ve_common.cmake - Common CMake utilities for VersatileEngine
# =============================================================================

# --- Collect all source/resource files for a module directory ---
# Convention:
#   include/*.h      — public headers
#   src/*.h/cpp      — private sources (+ .ui files)
#   res/*.qrc/*.ts   — Qt resources & translations
#
# Sets: ${PREFIX}_INCLUDES, ${PREFIX}_SOURCES, ${PREFIX}_UI, ${PREFIX}_QRC,
#       ${PREFIX}_TS, ${PREFIX}_ALL
macro(ve_collect VE_IN_DIR VE_OUT_PREFIX)
    file(GLOB_RECURSE ${VE_OUT_PREFIX}_INCLUDES CONFIGURE_DEPENDS ${VE_IN_DIR}/include/*.h)
    file(GLOB_RECURSE ${VE_OUT_PREFIX}_SOURCES CONFIGURE_DEPENDS
        ${VE_IN_DIR}/src/*.h
        ${VE_IN_DIR}/src/*.hpp
        ${VE_IN_DIR}/src/*.c
        ${VE_IN_DIR}/src/*.cpp
    )
    file(GLOB_RECURSE ${VE_OUT_PREFIX}_UI   CONFIGURE_DEPENDS ${VE_IN_DIR}/src/*.ui)
    file(GLOB_RECURSE ${VE_OUT_PREFIX}_QRC  CONFIGURE_DEPENDS ${VE_IN_DIR}/res/*.qrc)
    file(GLOB_RECURSE ${VE_OUT_PREFIX}_TS   CONFIGURE_DEPENDS ${VE_IN_DIR}/res/*.ts)
    # _ALL: all compilable / processable files + public headers.
    # Public headers are included so AUTOMOC can find Q_OBJECT classes
    # and generate the corresponding moc_*.cpp files.
    set(${VE_OUT_PREFIX}_ALL
        ${${VE_OUT_PREFIX}_INCLUDES}
        ${${VE_OUT_PREFIX}_SOURCES}
        ${${VE_OUT_PREFIX}_UI}
        ${${VE_OUT_PREFIX}_QRC}
        ${${VE_OUT_PREFIX}_TS}
    )
endmacro()

# --- Link Qt components to a target ---
# Usage: ve_target_link_qt(target VISIBILITY "Core;Network;Widgets")
macro(ve_target_link_qt VE_IN_TARGET VE_IN_VISIBILITY VE_IN_COMPONENTS)
    foreach(_qt_comp ${VE_IN_COMPONENTS})
        target_link_libraries(${VE_IN_TARGET} ${VE_IN_VISIBILITY} Qt${QT_VERSION_MAJOR}::${_qt_comp})
    endforeach()
endmacro()

# Resolve a module library target name from its base name.
# Example:
#   ve_resolve_library_target_name(VE_QT_LIBRARY veqt)
#   -> libveqt on Windows, veqt elsewhere
function(ve_resolve_library_target_name out_var base_name)
    if(WIN32)
        set(_resolved_name "lib${base_name}")
    else()
        set(_resolved_name "${base_name}")
    endif()

    set(${out_var} "${_resolved_name}" PARENT_SCOPE)
endfunction()

# Expose the canonical in-tree link target for the VE core library.
function(ve_add_core_library_alias target_name)
    if(NOT TARGET VersatileEngine::ve)
        add_library(VersatileEngine::ve ALIAS ${target_name})
    endif()
endfunction()

# --- Embed files into a target as byte arrays, readable via ve::res::read() ---
# Each file registers itself under a logical path. With ROOT given the relative
# part is "<path-relative-to-ROOT>", otherwise just "<filename>". The logical
# key is "<prefix>/<rel>" if PREFIX is given, else just "<rel>". Pure-CMake
# codegen, no external tooling. Editing an embedded file re-triggers configure.
#
# Usage:
#   ve_embed_files(<target> [PREFIX <p>] ROOT <dir> FILES <f1> <f2> ...)
function(ve_embed_files target)
    cmake_parse_arguments(EMB "" "PREFIX;ROOT" "FILES" ${ARGN})
    if(NOT EMB_FILES)
        return()
    endif()

    set(_gen_dir "${CMAKE_CURRENT_BINARY_DIR}/ve_embed/${target}")
    file(MAKE_DIRECTORY "${_gen_dir}")

    set(_gen_srcs "")
    set(_idx 0)
    foreach(_f ${EMB_FILES})
        if(EMB_ROOT)
            file(RELATIVE_PATH _rel "${EMB_ROOT}" "${_f}")
        else()
            get_filename_component(_rel "${_f}" NAME)
        endif()
        if(EMB_PREFIX)
            set(_logical "${EMB_PREFIX}/${_rel}")
        else()
            set(_logical "${_rel}")
        endif()

        file(READ "${_f}" _hex HEX)
        string(LENGTH "${_hex}" _hexlen)
        math(EXPR _len "${_hexlen} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
        if(_bytes STREQUAL "")
            set(_bytes "0x00,")  # avoid a zero-size array; _len stays 0
        endif()

        # Build with real newlines via JOIN — never rely on "\n" being interpreted
        # inside a literal (a single-line file would comment out everything after //).
        set(_lines
            "// generated by ve_embed_files() - do not edit"
            "#include \"ve/core/res.h\""
            "namespace {"
            "static const unsigned char k_data[] = { ${_bytes} }\;"
            "struct Registrar { Registrar() { ve::res::registerFile(\"${_logical}\", k_data, ${_len})\; } }\;"
            "static Registrar k_registrar\;"
            "}"
        )
        string(JOIN "\n" _content ${_lines})
        set(_out "${_gen_dir}/embed_${_idx}.cpp")
        file(WRITE "${_out}" "${_content}\n")

        list(APPEND _gen_srcs "${_out}")
        math(EXPR _idx "${_idx} + 1")
    endforeach()

    target_sources(${target} PRIVATE ${_gen_srcs})
    # Re-run configure when any embedded file changes so the bytes stay in sync.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${EMB_FILES})
endfunction()

# --- Embed a module's standard resource tree ---
# Convention wrapper over ve_embed_files(): globs everything under <module_dir>/res
# and embeds it rooted at <module_dir>/res. The logical key is
# "<prefix>/<path-relative-to-res>" if PREFIX is given, else just
# "<path-relative-to-res>". No-op when the module has no res/.
#
# Usage:
#   ve_collect_resources(<target> <module_dir> [PREFIX <p>])
function(ve_collect_resources target module_dir)
    cmake_parse_arguments(VCR "" "PREFIX" "" ${ARGN})
    file(GLOB_RECURSE _res_files CONFIGURE_DEPENDS ${module_dir}/res/*)
    if(VCR_PREFIX)
        ve_embed_files(${target} PREFIX ${VCR_PREFIX} ROOT ${module_dir}/res FILES ${_res_files})
    else()
        ve_embed_files(${target} ROOT ${module_dir}/res FILES ${_res_files})
    endif()
endfunction()
